//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSoftwareSolutions.Music {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PGSoftwareSolutions.Music.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFT120L16CO&lt;P16BAGP16FP16EP16GEP16DCP16EP16GP16ECDP16CP8P16O&gt;C
        ///.
        /// </summary>
        public static string QABC_CombineHarvester {
            get {
                return ResourceManager.GetString("QABC_CombineHarvester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T180 L4 O4
        ///C.D8E.C8 | ECE2 | D.E8F8F8E8D8 | F1 |
        ///E.F8G.E8 | GEG2 | F.G8A8A8G8F8 | A2..P8 |
        ///G.C8D8E8F8G8 | A1 | A.D8E8F#8G8A8 | B1 |
        ///B.E8F#8G#8A8B8 | &gt;C2.C8&lt;B8 | AFBG | &gt;C&lt;GED | C2.P4 |]
        ///.
        /// </summary>
        public static string QABC_Doe_a_deer {
            get {
                return ResourceManager.GetString("QABC_Doe_a_deer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFT150L16
        ///AP8EP8&gt;C&lt;P  | BP&gt;D&lt;PBPGP | AP8EP8&gt;C&lt;P  | BP&gt;D&lt;PBPGP  |
        ///&gt;CP8&lt;GP8&gt;EP | DPEPDP&lt;GP  | &gt;CP8&lt;AP8&gt;CP | &lt;BP&gt;CP&lt;BPGP |]
        ///.
        /// </summary>
        public static string QABC_Ecuador {
            get {
                return ResourceManager.GetString("QABC_Ecuador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MN T100 L8 O1
        ///A4 A. A16 | A4 &gt;C. &lt;B16 | B. A16 A. A16 | A2 |
        ///&gt;C4 C. C16 | C4 E.  D16 | D. C16 C. C16 | C2 |]
        ///.
        /// </summary>
        public static string QABC_FuneralMarch {
            get {
                return ResourceManager.GetString("QABC_FuneralMarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MF T60 L8 O3 
        ///CCD&lt;B&gt; P16 C16D | EEFE P16 D16C | DC &lt;B&gt; C4 P8 |
        ///CCD&lt;B&gt; P16 C16D | EEFE P16 D16C | DC &lt;B&gt; C4 P8 |]
        ///.
        /// </summary>
        public static string QABC_GodSaveTheQueen {
            get {
                return ResourceManager.GetString("QABC_GodSaveTheQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t200l4o4mn
        ///eee2 | eee2 | egc.d8 | e1 | fff.f8 | fee2 | e8e8edd | ed2g. p8 |
        ///eee2 | eee2 | egc.d8 | e1 | fff.f8 | fee2 | e8f8ggf | dc1
        ///.
        /// </summary>
        public static string QABC_JingleBells {
            get {
                return ResourceManager.GetString("QABC_JingleBells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MN T180 O2 L8
        ///C4CCC4CC | CCCCCE&lt;GG&gt; | C4CCC4CC | CCCC&lt;A4G4&gt; |
        ///C4CCC4CC | CCCCE4G4   | G2EPGE   | P4C2P4 |]
        ///.
        /// </summary>
        public static string QABC_Macarena {
            get {
                return ResourceManager.GetString("QABC_Macarena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MF T120 L16 O4
        ///C&lt;A#&gt;C&lt;G | D#GC P | &gt;C&lt;A#&gt;C&lt;G | D#GC P |
        ///&gt;CDD#D   | D#CDC  | D&lt;A#&gt;C&lt;A# | &gt;C&lt;G#&gt;C P4 |]
        ///.
        /// </summary>
        public static string QABC_Popcorn {
            get {
                return ResourceManager.GetString("QABC_Popcorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mn t200 l4 o3
        ///C pc | AG E | ml G2. | D2D | mn C pc | AG E | ml G2. |
        ///mn AG+A | E FG | A2 F | ml D2D | mn A2A | A Bc | dB A | GED |
        ///C pc | AG E | ml G2. | mn D2D | C2D | EFG | ml A2. | 
        ///p mn AB | c. | p. | c. | p. | cBA | GF+G | ml A2. | B2. | c2. |].
        /// </summary>
        public static string QABC_TakeMeOutToTheBallGame {
            get {
                return ResourceManager.GetString("QABC_TakeMeOutToTheBallGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T160 L4 
        ///MS F G A8 G A8 | B- A G8 F G8 | MS A G F A  MS G1 |  
        ///MS F G A8 G A8 | B- A G8 F G8 | MS A G F A  MS F1 |] 
        ///.
        /// </summary>
        public static string QABC_TheLionSleepsTonight {
            get {
                return ResourceManager.GetString("QABC_TheLionSleepsTonight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T150 L8 MN O3
        ///B&gt;C4MLD2. &lt;B&gt;C&lt;B&gt;E2. PCDE2..EEDCE2. E4G4 ED2.. P8
        ///&lt;G4B&gt;C&lt;B4 A1. P2 
        ///B&gt;DD4D&lt;B&gt;DmlE D2P2 mn
        ///EGGE GEMLAG EDD2MNDE 
        ///MLBAGED4&lt;BA G2MNGAG4 ML&gt;DC&lt;B2. P1
        ///P1
        ///
        ///T150 L16 ML O2
        ///e4 degb &gt;egb&gt;e gb2 b2. g8..f+32f+8p8&gt;d8.&lt;b b4.p8p4
        ///&lt;&lt;f+4 e+f+ab &gt;d+f+b&gt;e+ f+b2 b2. a8..g32g8 &gt;c8.&lt; b16b4.p8p4
        ///&lt;g4.
        ///.
        /// </summary>
        public static string QABC_Unknown {
            get {
                return ResourceManager.GetString("QABC_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mf l16 t155
        ///o3mnB4p8msBBmnB4p8msBBB8G#8
        ///E8G#8B8G#8B8&gt;E8o&lt;B8G#8E8G#8
        ///B8G#8B8 o&gt; E8 &lt; mnB4p8msBBmnB4
        ///p8msBBmnB4p8msBBmnB4p8msBB
        ///B8BBB8B8B8BBB8B8B8BB
        ///B8B8B8BBB8B8B2..p8p4p4
        ///p8mso1BBB8BBB8BBo2E8F#8G#8o1BB
        ///B8BBo2E8G#G#F#8D#8o1B8BBB8BB
        ///B8BBo2E8F#8G#8EG#mlB4BmsAG#F#
        ///E8G#8E8o3BBB8BBB8BBo4E8F#8
        ///G#8o3BBB8BBo4E8G#G#F#8D#8o3B8BB
        ///B8BBB8BBo4E8F#8G#8mlEG#B4
        ///BAG#F#msE8G#8E8o3G#G#G#8G#G#G#8G#G#
        ///G#8o4C#8o3G#8o4C#8o3G#8o4C#8o3G#8F#8E8D#8
        ///C#8G#G#G#8G#G#G#8G#G#G#8o4C#8o3G#8o4C#8
        ///o3G#8o4C#8o3B8A#8B8A#8B8G#G#G#8G# [rest of string was truncated]&quot;;.
        /// </summary>
        public static string QABC_WillTell {
            get {
                return ResourceManager.GetString("QABC_WillTell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MN T255 L4 O2
        ///GGAB  | GBAD | GGAB | G2F+2  | GGAB  | &gt;C&lt;BAG | F+DEF+| G2GP |
        ///EF+ED | EF+G2| DEDC | &lt;B2&gt;D2 | EF+ED | EF+GE | DGF+A | G2GP1 |
        ///
        ///MN T255 L4 O3
        ///GGAB  | GBAD  | GGAB | G2F+2  | GGAB  | &gt;C&lt;BAG | F+DEF+ | G2GP |
        ///EF+ED | EF+G2 | DEDC | &lt;B2&gt;D2 | EF+ED | EF+GE  | DGF+A  | G2GP |]
        ///.
        /// </summary>
        public static string QABC_YankeeDoodle {
            get {
                return ResourceManager.GetString("QABC_YankeeDoodle", resourceCulture);
            }
        }
    }
}
